spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        format_sql: true
      org.hibernate:
        envers:
          audit_table_suffix: _audit
          revision_field_name: revision_id
          revision_type_field_name: revision_type
    show-sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lab1
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    rest:
      detection-strategy: annotated
      base-path: /api
      max-page-size: 100
      default-page-size: 10

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jackson:
    deserialization:
      accept-empty-string-as-null-object: false
      accept-empty-array-as-null-object: false
      fail-on-null-for-primitives: true

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /

security:
  basic:
    enable: false
  ignored: /**

server:
  address: 0.0.0.0